### ISSUE TITLE
editor-ready event not firing

### ISSUE THREAD

**Issue by brianreeve** [LostInBrittany/ace-widget#1]
https://github.com/LostInBrittany/ace-widget/#events

Per the README, an editor-ready is triggered when the Ace instance is created. However, it doesn't appear to be firing.

On further inspection, editor-content is the only event that appears to be fired from https://github.com/LostInBrittany/ace-widget/blob/master/ace-widget.html

**Comment by runn-vermel** [comment]
sadly, although I see it in your code, it's still not firing for me. :(
