### ISSUE TITLE
Editor gets focused on value change

### ISSUE THREAD

**Issue by jhrdina** [LostInBrittany/ace-widget#10]
Hello,
I've run into a small issue with focus.

Editor gets focused everytime `value` attribute is changed from outside. I don't feel like this is a correct behavior. Imagine you want to use ace-widget only as a _viewer_. Anytime you edit value from some external textarea (or whatever), focus gets stolen by the ace-widget.

**Comment by LostInBrittany** [comment]
Thanks for the issue!

What would be, in your opinion, the right behaviour?

**Comment by jhrdina** [comment]
I think the ace-widget shouldn't get focused after changing the value. It should get focus only after user clicks on it or so. 

I would simply remove the `this.editor.focus();` line from `valueChanged` method.

**Comment by LostInBrittany** [comment]
I think there was a reason why I added that focus, I'am almost sure... but right now I'm unable to remember it.

I'm editing out the focus call, and if needed, I'll add a parameter to configure it.

Thanks again!

**Comment by jhrdina** [comment]
Sounds good! Thanks for your fast response.
