### ISSUE TITLE
Doesn't work with Polymer 2

### ISSUE THREAD

**Issue by cleaverpj** [LostInBrittany/ace-widget#17]
There is a runtime error with Polymer 2 in ace-widget-shadow-dom

Polymer.StyleProperties does not exist.

Editor fails to show :(

**Comment by valpackett** [comment]
yeah and `Polymer.DomApi.matchesSelector` also doesn't exist (most of the DOM wrapping is gone)

**Comment by LostInBrittany** [comment]
I'm working on a new version, playing nice with Polymer 2.0

**Comment by LostInBrittany** [comment]
Yesterday I've released an hybrid version that works on Polymer 1.x and 2.x. It should solve your problems, please reopen if needed.
