### ISSUE TITLE
"var" missing, line 10 of ace-widget-shadow-dom.html

### ISSUE THREAD

**Issue by twinforces** [LostInBrittany/ace-widget#21]
This causes a problem when ace-widget-shadow-dom.html loads after "use strict" has been seen. 

![screen shot 2018-04-18 at 6 22 02 pm](https://user-images.githubusercontent.com/711888/38966125-6d1ed67c-4335-11e8-918f-3d3aa78bc900.png)

**Comment by LostInBrittany** [comment]
Fixed by #22, thanks!
