### ISSUE TITLE
Polymer 3

### ISSUE THREAD

**Issue by martinlindemann** [LostInBrittany/ace-widget#24]
I want to use the ace-widget component in another polymer 3 component.

Is a version for polymer 3 planned for ace-widget or already in progress?

**Comment by LostInBrittany** [comment]
Already in progress :)

I hope to release it by the end of the week.

On Mon, Jun 11, 2018 at 10:51 AM, Martin Lindemann <notifications@github.com

**Comment by martinlindemann** [comment]
I have tried to use the polymer 3 component. The component is working with chrome but if i want to use firefox i get an error. Same error if i want to see the demo page from ace-wdget. 

Error message from firefox: 
![console-error](https://user-images.githubusercontent.com/38466479/43392015-adf46e42-93f2-11e8-9a53-985a773bd393.png)

Do you have any idea or are you already working on this .

**Comment by LostInBrittany** [comment]
Ouch, sorry for the late delay, I am in vacances and I try to keep myself
far from the computer :)

I will look at it early next week.

**Comment by LostInBrittany** [comment]
Added dynamic import of ace and dependencies, and fixed bad link to polyfill in demo.

Still not happy about the dynamic import, looking for a better solution...

**Comment by LostInBrittany** [comment]
I've just released 2.2.0, it should fix problems with Firefox without forcing the dynamic import

**Comment by martinlindemann** [comment]
The component is working as expected in chrome, firefox and edge but the error messages are still in the console.

Update: Ok i can see the editor in firefox ad edge but i cannot type into the editor

**Comment by LostInBrittany** [comment]
You should see some errors in console in Firefox, as the import system is asynchronous and the ace modules are imported before ace (AFAIK it's not possible to do synchronous declarative imports) but it only happens in dev, after building/bundling the code is synchronously loaded and the errors disappear. So to make it work on dev, I test if the imports are done well and if not I do some dynamic importing, it works but you still have the initial errors in the console.

As for the problem with being unable to edit in Firefox, I have just fixed it in release 2.2.5, can you please verify it works for you?

Thanks again for your feedback!

**Comment by martinlindemann** [comment]
Editor works in chrome and in firefox now. In edge the editor is not loaded.

Live autocompletion is not working: 
-the window with autocomletion is displayed but it is empty.
-when you type the same key two times again the editor detects three letters. (If i disable autocompletion this is not happening)

**Comment by LostInBrittany** [comment]
Thanks for the feedback!

I will look at the Edge problem as soon as I grab a Windows computer.
Looking at the auto-completion this afternoon.

Thanks again!

**Comment by martinlindemann** [comment]
Editor is loaded in Edge Version 42.17134.1.0
