### ISSUE TITLE
Getting random text in editor.

### ISSUE THREAD

**Issue by rohanpansare** [LostInBrittany/ace-widget#9]
Hi,
    This is Rohan. I had some doubt , I embedded ace-widget tag in polymer webpage. I am getting this text "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" in the editor.
Could you please let me know the source of error. Please find attachment.
Thanks,
Rohan.

![screenshot 66](https://cloud.githubusercontent.com/assets/3147767/14481966/b4a8021c-0105-11e6-9b6c-7d0264e02479.png)
![screenshot 67](https://cloud.githubusercontent.com/assets/3147767/14481967/b4a94f3c-0105-11e6-908f-8c4179ababd8.png)

**Comment by LostInBrittany** [comment]
Sorry, it's a case of bad initialisation, when no initial code is given the default is that 'XXXXX....'

I'm going to correct that to have a more sensible default, like an empty text...

Thanks for the issue!

**Comment by LostInBrittany** [comment]
Are you sure you're using the latest version of the widget?

I've just tested with it, the problem isn't there anymore.

I've added a test on `demo/index.html` with empty content.

Could you please test the last with Polyserve or integrating it in your project?

**Comment by rohanpansare** [comment]
Hi,
     I updated the widget now. I am not seeing the "XXXXXX..." text in the editor now but when reading the text using the editor.getSession().getValue() method it appends the linenumber and "XXXX.." text at the end of the editor text . Please see attachment.

ace-widget id="editor" theme="ace/theme/monokai" mode="ace/mode/json"
{Some Text}
                  ace-widget
After entering some text I did this 
      var editor = ace.edit("editor");
      var myVar = editor.getSession().getValue();
      alert(myVar);

Thanks,
Rohan.
![pasted_image_at_2016_04_13_12_40_pm](https://cloud.githubusercontent.com/assets/3147767/14501609/464edf00-0175-11e6-8392-5a408ba37634.png)

**Comment by LostInBrittany** [comment]
Going to test it, and correct it, thanks!

**Comment by LostInBrittany** [comment]
I've done an explicit initialization to `''`, so you shouldn't find that problem anymore.

I've also added a log at the end of the initialization method to show the current value, you can see it in `demo/index.html` to be sure that in the case of empty content the value is also empty.

Can you please test it agais and tell me if it works for you ?

![demo/index.html](http://lostinbrittany.com/content/images/2016/04/ace-widget.png)
